### ISSUE TITLE
Should list IO::Socket::PortState as a dependency

### ISSUE THREAD

**Issue by jwm** [mattn/p5-Growl-GNTP#6]
Growl::GNTP won't work without IO::Socket::PortState, but it isn't listed as a dependency in cpanfile or META.*.

**Comment by kentfredric** [comment]
can somebody clarify /why/ it doesn't work without IO::Socket::PortState? I don't see it used anywhere in code.

**Comment by mattn** [comment]
Right, I don't remember why i did add this. Will remove in later if no problems.

**Comment by kentfredric** [comment]
If somebody works out why, perhaps a test could be added to demonstrate it, would remove doubt =)

**Comment by kentfredric** [comment]
Bah. Sorry about the git commit reference spam. I really wish github wasn't so magical :/

**Comment by mattn** [comment]
removed dependency of IO::Socket::PortState.
