### ISSUE TITLE
Can't use string ("Name") as a HASH ref while "strict refs" in use...

### ISSUE THREAD

**Issue by dasgar** [mattn/p5-Growl-GNTP#7]
I installed Growl::GNTP (version 0.20) in portable Strawberry Perl 5.20.0.1 32-bit.

It looks like Perl is complaining about code inside the module itself.  The error message that I got was:

Can't use string ("Name") as a HASH ref while "strict refs" in use at C:/strawberry-perl-5.20.0.1-32bit-portable/perl/site/lib/Growl/GNTP.pm line 67.

I did have 'use strict;' in my code.  Even after commenting out that line from my code, I got the same error message.  In looking at GNTP.pm source code, it is also calling 'use strict;'.

Here is the code used to produce this error message:

#use strict;
#use warnings;

use feature 'say';

use Growl::GNTP;

my $app = 'my-app';
my $passwd = 'my-password';

my $growl = Growl::GNTP->new(
	AppName => $app,
	Password => $passwd,
);

$growl->register ([
	Name => 'my-app',
	DisplayName => 'my-app',
	Enabled => 'True',
]);

$growl->notify(
	Name => 'Name1',
	Title => 'Title1',
	Message => 'Message1',
);

**Comment by mattn** [comment]
Try below:

```perl
$growl->register ([
    {
        Name => 'my-app',
        DisplayName => 'my-app',
        Enabled => 'True',
    },
]);
```

**Comment by dasgar** [comment]
After I made the suggested change to my code,  I was getting the following error message:

Invalid key hash at C:/strawberry-perl-5.20.0.1-32bit-portable/perl/site/lib/Growl/GNTP.pm line 114.

That line looks to be in the register subroutine.  The wording of that message at first made me think that there's a problem with my code or code in the module, but the die statement in that specified line of the module made me decide to double-check the options that were being set.  Then I realized that I still had the sanitized 'my-password' text instead of the real password and that I needed to change the PasswordHashAlgorithm.  After fixing that, the "app" did get registered, but I hit another issue (problem in my code's call to the notify subroutine and not in the module itself).

So the new problem mentioned above was due to login/connection issues (password and password hash algorithm).  But the error message seemed to indicate coding issue in either my code or the module.  If there was some way to provide a more useful error message (maybe something like 'Unable to login/register') when there is a connection issue due to options being set incorrectly, that would help the user realize that the problem was with options not being set correctly as opposed to bugs in the code.

**Comment by mattn** [comment]
What app do you use for Growl-Server? Growl for Windows?

**Comment by dasgar** [comment]
Yes. Growl for Windows (v2.0.9).  After doing some testing, it apparently is using SHA1 for its password hash algorithm.  (Using only the GUI interface, this is not a setting that can be changed.)

**Comment by mattn** [comment]
What your configuration about `Security` tab?

![](http://go-gyazo.appspot.com/c8af42daf4751b82.png)

**Comment by dasgar** [comment]
At the moment, my settings match your screenshot.

Yesterday I was doing some testing using the growlnotify.exe that comes with Growl for Windows.  During that testing, I was trying to select/deselect the two "Require password" options.  I don't remember which combinations I tried and didn't really make any notes about that.

**Comment by mattn** [comment]
I set 123 to password. And checked two options.

![](http://go-gyazo.appspot.com/33e94ce596545b39.png)

```perl
use strict;
use warnings;

use feature 'say';

use Growl::GNTP;

my $app = 'my-app';
my $passwd = '123';

my $growl = Growl::GNTP->new(
    AppName => $app,
    Password => $passwd,
);

$growl->register ([{
    Name => 'my-app',
    DisplayName => 'my-app',
    Enabled => 'True',
}]);

$growl->notify(
    Name => 'my-app',
    Title => 'Title1',
    Message => 'Message1',
);
```
It seems working for me.

![](http://go-gyazo.appspot.com/a37f55c940871866.png)

BTW, why do you set Name as `Name1` ? Should be `my-app` ?
